# mkdocs.yml
site_name: Helldive.py
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [./]  # Path to your source code
          options:
            members: true
            members_order: source
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_root_members_full_path: true
            show_object_full_path: true
            show_category_heading: true
            show_if_no_docstring: true
            filters:
              - "!^_"  # Exclude private members (starting with underscore)
              - "!^__"  # Exclude special members (starting with double underscore)
            docstring_section_style: spacy
            merge_init_into_class: true
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
            docstring_style: google
nav:
  - Home: index.md
  - API Reference:
      - Overview: api/index.md
      - Module Name:
          - api/constants.md
          - api/enums.md
          - api/models.md
          - api/routes.md
          - api/utils.md