# mkdocs.yml
site_name: Helldive.py
site_description: Docs for the helldive.py library.
site_author: AJXD2
site_url: https://ajxd2.github.io/helldive.py/

repo_name: ajxd2/helldive.py
repo_url: https://github.com/ajxd2/helldive.py


theme: 
  name: material
  icon:
    logo: material/cog
  language: en
  features:
    - navigation.sections
    - navigation.tabs
    - content.code.copy
    - content.code.select
  palette:
    scheme: slate
    primary: teal
    accent: teal
plugins:
  
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [./]  # Path to your source code
          options:
            members: true
            members_order: source
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_root_members_full_path: true
            show_object_full_path: true
            show_category_heading: true
            show_if_no_docstring: true
            filters:
              - "!^_"  # Exclude private members (starting with underscore)
              - "!^__"  # Exclude special members (starting with double underscore)
            docstring_section_style: spacy
            merge_init_into_class: true
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
            docstring_style: google
nav:
  - Home:
    - Introduction: index.md 
    - Installation: installation.md
    
  - API Reference:
      - Overview: api/index.md
      - Helldive.py:
          - api/constants.md
          - api/enums.md
          - api/models.md
          - api/routes.md
          - api/utils.md
      
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - footnotes
  - codehilite
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences